# Generated by Django 5.0 on 2024-05-28 12:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='upload')),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone_num', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('location', models.TextField(blank=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_payed', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('orig_price', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('image1', models.ImageField(upload_to='upload')),
                ('image2', models.ImageField(blank=True, upload_to='upload')),
                ('image3', models.ImageField(blank=True, upload_to='upload')),
                ('price', models.IntegerField(default=0)),
                ('old_price', models.IntegerField(blank=True, default=0)),
                ('compound', models.TextField(blank=True)),
                ('storage_cond', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('discount', models.IntegerField(default=0)),
                ('is_new', models.BooleanField(default=True)),
                ('rating', models.FloatField(blank=True, default=0.0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
